"""crear tablas iniciales

Revision ID: cf64cfece415
Revises: 
Create Date: 2025-06-14 18:42:16.152167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf64cfece415'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dreams', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('dreams', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dreams', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dreams', 'interpretation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dreams', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'dreams', 'users', ['user_id'], ['id'])
    op.add_column('subscriptions', sa.Column('plan_name', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('dreams_allowed', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('dreams_used', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.drop_column('subscriptions', 'used_dreams')
    op.drop_column('subscriptions', 'max_dreams')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'dreams_used')
    op.drop_column('users', 'dream_quota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dream_quota', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dreams_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('subscriptions', sa.Column('max_dreams', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('used_dreams', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'dreams_used')
    op.drop_column('subscriptions', 'dreams_allowed')
    op.drop_column('subscriptions', 'plan_name')
    op.drop_constraint(None, 'dreams', type_='foreignkey')
    op.alter_column('dreams', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dreams', 'interpretation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dreams', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dreams', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('dreams', 'user_id')
    # ### end Alembic commands ###
